#!/bin/bash
#
#
#Script: Anal_boltz.sh
#Purpose: extracts boltz output affinity .json files into .csv format and combines for all files in a folder
#Author: J_dog Leitz
#Date: 2025-08-23
#Usage ./Anal_boltz.sh -i <input directory> -o <output directory> [-w]
#
#Description:
#Searches for affinity*affinity.json files in the Output directory and concatenates them and combines them into a csv file.
#
#Dependencies: Requires jq installed

#Parse arguments
while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
		-i|--Input) 
			InputDIR="$2"  #Should be the Nutz folder that contains "Ligand_yamls" folder
			shift
			shift
			;;
		-o|--Output)
			OutputDIR="$2"
			shift
			shift
			;;
		-w|--overwrite)
			overwrite=true
			shift
			;;
		 *)
			echo "usage: $0 -i <Input Directory that contains 'Ligand_yamls' directory> -o <Output Directory> [-w/--overwrite]"
			exit 1
		esac
done

# Source the conda setup to make the `conda` command available.
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate boltz

#Create output directory, if needed.
if [[ ! -d "$OutputDIR" ]]; then mkdir -p $OutputDIR; fi

#Check that the input directory exists
if [[ ! -d "$InputDIR"/Ligand_yamls ]]; then 
	echo "could not find $InputDIR/Ligand_yamls, check that it exists"
	exit 1
else
	fileNUM=$(find $InputDIR/Ligand_yamls -name "affinity*.json" | wc -l)
	if [ $fileNUM -eq 0 ]; then 
		echo "Found the directory ${InputDIR}/Ligand_yamls, but it appears to be empty!"
		exit 1
	else
		echo "Found ${fileNUM} files!  Processing now..."
		first_file=$(find $InputDIR/Ligand_yamls -name "affinity*.json" | head -n 1)		

		#Check if output file exists, if not create it/overwrite it, or exit
		if [[ ! -f "$OutputDIR"/combined.csv ]]; then
       			 jq -r '["filename", "Receptor", "Drug"] + keys_unsorted | @csv' $first_file > $OutputDIR/combined.csv
		else
        		if [[ $overwrite == "true" ]]; then
                		echo "Found existing combined.csv file, overwriting it...."
                		jq -r '["filename", "Receptor", "Drug"] + keys_unsorted | @csv' $first_file > $OutputDIR/combined.csv
        		else
                		echo "File $OutputDIR/combined.csv alread exists. Use -w or --overwrite flag to overwrite it."
                		exit 1
       			fi
		fi
		
		#Process the files
		find $InputDIR/Ligand_yamls/ -name "affinity*.json" | while read -r file; 
		do 
			# Validate JSON before processing
			if ! jq empty "$file" 2>/dev/null; then
    				echo "Warning: Skipping malformed JSON: $file"
    				continue
			fi

			basename_file=$(basename $file); 
			target=$(echo $basename_file | cut -d '_' -f2); 
			compound=$(echo $basename_file | cut -d '_' -f3); 
	
			jq -r --arg filename "$basename_file" --arg Receptor "$target" --arg Drug "$compound" '[$filename, $Receptor, $Drug] + [.[]] | @csv' $file >> $OutputDIR/combined.csv 
		done
	fi
fi

echo "All done analyzing, boss!"
