#!/bin/bash
# Runs Boltz-2 on a chunk of SMILES against one or more protein chains.
# Expects to be called by a SLURM array job generated by Deez.sh, which
# guarantees that:
#   - Chunk files are clean two-column CSVs (smiles, name) with a header row
#   - MSA files are always provided (generated by pilot job or user-supplied)
#
# Supports arbitrary protein chains via comma-separated -p and -m lists:
#   -p fasta1.fasta,fasta2.fasta
#   -m msa1.a3m,msa2.a3m
#
# Written by Jeremy Leitz @ Greenstone Biosciences
# https://github.com/Greenstone-Biosciences/boltz2-hpc-tools

start_time=$(date +%s)

Usage="Usage: $0 -i <input_dir> -p <fasta1,fasta2,...> -m <msa1,msa2,...>"

# ---------- Argument parsing ----------

while [[ $# -gt 0 ]]; do
    case $1 in
        -i|--input)      Input="$2";       shift; shift ;;
        -p|--prot_fasta) Prot_Fastas="$2"; shift; shift ;;
        -m|--use_msa)    Use_MSAs="$2";    shift; shift ;;
        *) echo "Unknown option: $1"; echo "$Usage"; exit 1 ;;
    esac
done

# ---------- Validation ----------

[[ -z "$Input" ]]       && { echo "ERROR: -i input directory is required."; exit 1; }
[[ -z "$Prot_Fastas" ]] && { echo "ERROR: -p fasta file(s) are required.";  exit 1; }
[[ -z "$Use_MSAs" ]]    && {
    echo "ERROR: -m MSA file(s) are required."
    echo "       Deez.sh should have generated or located MSA files before"
    echo "       submitting this job. Did the pilot job complete successfully?"
    exit 1
}

[[ ! -d "$Input" ]] && { echo "ERROR: Input directory not found: $Input"; exit 1; }

# ---------- Environment ----------

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate boltz

# ---------- Chunk setup ----------

padded_id=$(printf "%04d" $SLURM_ARRAY_TASK_ID)
cd "$Input"

mkdir -p "Nut_${padded_id}/Ligand_yamls"

mv "$Input/chunk_${padded_id}" "$Input/Nut_${padded_id}/"
working_file="${Input}/Nut_${padded_id}/chunk_${padded_id}"

if [[ ! -f "$working_file" ]]; then
    echo "ERROR: Could not find chunk file: $working_file"
    exit 1
fi

echo "Processing chunk: $working_file"
echo "Compounds in chunk: $(( $(wc -l < "$working_file") - 1 ))"

# ---------- Parse and validate fasta/MSA lists ----------

IFS=',' read -ra fasta_arr <<< "$Prot_Fastas"
IFS=',' read -ra msa_arr   <<< "$Use_MSAs"

n_proteins=${#fasta_arr[@]}
echo "Protein chains: ${n_proteins}"

for fasta in "${fasta_arr[@]}"; do
    fasta="${fasta// /}"
    [[ ! -f "$fasta" ]] && { echo "ERROR: FASTA not found: $fasta"; exit 1; }
done

for i in "${!msa_arr[@]}"; do
    msa="${msa_arr[$i]// /}"
    [[ -z "$msa" ]] && { echo "ERROR: Empty MSA slot for chain $((i+1))."; exit 1; }
    [[ ! -f "$msa" ]] && { echo "ERROR: MSA file not found: $msa"; exit 1; }
    if od -c "$msa" | grep -q "\\\\0"; then
        echo "  Null bytes found in MSA for chain $((i+1)), cleaning..."
        cleaned="$(dirname "$msa")/uniref_clean.a3m"
        tr -d '\0' < "$msa" > "$cleaned"
        msa_arr[$i]="$cleaned"
    fi
done

echo "All FASTA and MSA files validated."

# Rebuild MSA string from array (may have been updated by null byte cleaning)
Use_MSAs=$(IFS=','; echo "${msa_arr[*]}")

# ---------- YAML generation loop ----------
# Chunk files are clean two-column CSVs written by Deez.sh:
#   header: smiles,name
#   data:   <smiles_string>,<compound_id>

echo ""
echo "Generating YAMLs in ${Input}/Nut_${padded_id}/Ligand_yamls"

skip_log="${Input}/Nut_${padded_id}/skipped_compounds.tsv"

tail -n +2 "$working_file" | while IFS=',' read -r smile name || [[ -n "$smile" ]]; do
    smile=$(echo "$smile" | tr -d '\r\n "')
    name=$(echo "$name"  | tr -d '\r\n "')

    [[ -z "$smile" ]] && continue

    echo "  $name"

    python3 - << PYEOF
import string, json, sys

fasta_files = "${Prot_Fastas}".split(",")
msa_files   = "${Use_MSAs}".split(",") if "${Use_MSAs}" else []
smile       = "${smile}"
name        = "${name}"
out_dir     = "${Input}/Nut_${padded_id}/Ligand_yamls"
skip_log    = "${skip_log}"

from rdkit import Chem
from rdkit.Chem import rdBase
rdBase.DisableLog("rdApp.error")
mol = Chem.MolFromSmiles(smile)
if mol is None:
    print(f"  WARNING: RDKit could not parse SMILES for '{name}' — skipping.")
    with open(skip_log, "a") as sf:
        sf.write(f"{name}\t{smile}\tINVALID_SMILES\n")
    sys.exit(0)

chain_ids = list(string.ascii_uppercase)
sequences = []

for i, fasta in enumerate(fasta_files):
    with open(fasta.strip()) as f:
        seq = f.read().strip()
    entry = {"id": chain_ids[i], "sequence": seq}
    msa = msa_files[i].strip() if i < len(msa_files) else ""
    if msa:
        entry["msa"] = msa
    sequences.append({"protein": entry})

ligand_id = chain_ids[len(fasta_files)]
sequences.append({"ligand": {"id": ligand_id, "smiles": smile}})

doc = {
    "version": 1,
    "sequences": sequences,
    "properties": [{"affinity": {"binder": ligand_id}}]
}

out_path = f"{out_dir}/{name}_affinity.yaml"
with open(out_path, "w") as f:
    json.dump(doc, f, indent=2)
PYEOF

done

# ---------- Boltz predict ----------

echo ""
echo "Running boltz predict on chunk ${padded_id}..."
cd "${Input}/Nut_${padded_id}"
boltz predict ./Ligand_yamls

if [[ -f "$skip_log" ]]; then
    echo ""
    echo "WARNING: $(wc -l < "$skip_log") compound(s) were skipped due to invalid SMILES."
    echo "  See: $skip_log"
fi

echo "Chunk ${padded_id} complete."

end_time=$(date +%s)
runtime=$(( end_time - start_time ))
echo "Runtime: $(date -ud "@$runtime" +'%H:%M:%S')"
