#!/bin/bash
#This is for running boltz-2 on a group of ligands
#Input is file containing smiles and names of ligands
#Requires that user has already run Deez.sh which fetches protein fasta and optionally splits the smiles file by array task and generates sbatch executable

start_time=$(date +%s)
Usage="Usage: $0 -i|--input <input_file> -p|--prot_fasta <prot_fasta_file> [-m|--use_msa]"

#Arguments
while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
		-i|--input)
		Input="$2"
		shift # past argument
		shift # past value
		;;
		-p|--prot_fasta)
		Prot_Fasta="$2"
		shift # past argument
		shift # past value
		;;
		-m|--use_msa)
		USE_MSA="$2"
		shift # past argument
		shift # past value
		;;
		*)
		echo "Unknown option: $1"
		echo "$Usage" 
		exit 1
		# unknown option
		;;
	esac
done

#Input=$1 #Path to directory of "chunk" files generated by Deez.sh (can be single file)
#Prot_Fasta=$2 #Full path to the file containing the protein fasta

# Source the conda setup to make the `conda` command available.
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate boltz

#Get the chunk_id to use
padded_id=$(printf "%04d" $SLURM_ARRAY_TASK_ID)

#Navigate to Nutz directory
cd "$Input"

#Move chunk into Ligand_yamls and set as working_file
mv $Input/chunk_${padded_id} $Input/Ligand_yamls/
working_file=${Input}/Ligand_yamls/chunk_${padded_id}

#Check that the working file is there
if [[ ! -f $working_file ]]; then
	echo "could not find ${working_file}, looked in ${Input/Ligand_yamls/} for chunk_$padded_id"
	exit 1
else
echo "Processing input file: ${working_file}"
echo "Number of compounds: $(wc -l < $working_file)"
fi

#Get the fasta sequence of the protein
sequence=$(cat "$Prot_Fasta")

	#Pull the smiles and names from the input file and make affinity yaml
	for i in $(seq 1 $(wc -l < "$working_file"));
	do
		line=$(sed "${i}q;d" $working_file);
		#Check if the file is comma separated or space separated
		if sed '2q;d' $working_file | grep -q ',' ; then 
			smile=$(echo $line | cut -d ',' -f1)
			name=$(echo $line | cut -d ',' -f2)
		else
			smile=$(echo $line | awk '{ print $1 }');
			name=$(echo $line | awk '{ print $2 }');
		fi
		#Check if the results exist.
		if [[ ! -f ${Input}/Ligand_yamls/boltz_results_${name}_affinity/predictions/*/affinity*affinty.json ]]; then

			echo "Processing compound $i: $name from file $working_file"

			#Create YAML file for this compound
			if [ -n "$USE_MSA" ]; then
				echo "Using MSA from: $USE_MSA"
				#Check that the msa doesn't contain any null bytes
				if od -c "$USE_MSA" | grep -q "\\\\0"; then
					echo "Null bytes were found in the MSA file. Cleaning..."
					#Make a cleaned version of the MSA file
					tr -d '\0' < "$USE_MSA" > "${USE_MSA}_clean.a3m"
					USE_MSA="${USE_MSA}_clean.a3m"
				else
					echo "MSA file appears clean"
				fi
				yq --arg seq "$sequence" --arg msa "$USE_MSA" --arg smi "$smile" '.sequences[0].protein.sequence = $seq | .sequences[0].protein.msa = $msa | .sequences[1].ligand.smiles = $smi' ~/Software/boltz/affinity_template.yaml > ${Input}/Ligand_yamls/${name}_affinity.yaml;
			else
				echo "no MSA provided, using server"
				yq --arg seq "$sequence" --arg smi "$smile" '.sequences[0].protein.sequence = $seq | del(.sequences[0].protein.msa) | .sequences[1].ligand.smiles = $smi' ~/Software/boltz/affinity_template.yaml > ${Input}/Ligand_yamls/${name}_affinity.yaml;
			fi

			#move into Ligand_yamls folder
			cd ${Input}/Ligand_yamls
			if [ -n "$USE_MSA" ]; then
				echo "using $USE_MSA"
				boltz predict "${name}_affinity.yaml" 
			else
				echo "no MSA provided, using server"
				boltz predict "${name}_affinity.yaml" --use_msa_server
			fi

			echo "finished prediction on ${name}"
		else
			echo "${Input}/Ligand_yamls/boltz_results_${name}_affinity/predictions/*/affinity*affinty.json already exists."
			continue
		fi
	done

end_time=$(date +%s)
runtime=$(($end_time - $start_time))
echo "Total runtime: $(date -ud "@$runtime" +'%H:%M:%S')"
echo "Total runtime was: $runtime"
