#!/bin/bash
#This is for running boltz-2 on a group of ligands 
#Input is file containing smiles and names of ligands
#Requires that user has already run Deez.sh which fetches protein fasta and optionally splits the smiles file by array task and generates sbatch executable

#Arguments
Input_file=$1 #Directory of "chunk" files generated by Deez.sh (can be single file)
Output_Dir=$2
Prot_Fasta=$3 #Full path to the file containing the protein fasta

# Source the conda setup to make the `conda` command available.
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate boltz

#Make output dir
mkdir -p "$Output_Dir"
cd "$Output_Dir"

#If run as single sbatch, create and Move into the Output directory 
if [ -n "${SLURM_ARRAY_TASK_ID}" ];
then
	echo "Running as an array job, task ID: $SLURM_ARRAY_TASK_ID"
	taskNO=$(printf "%02d" $SLURM_ARRAY_TASK_ID)

	#Create Chuck directories

	mkdir -p ./Chunk_${TaskNO}
	cd Chunk_${TaskNO}
	
	#make Ligand DIR
	mkdir -p ./Ligand_yamls
	LigandDIR=./Ligand_yamls

	#Copy the split file for this task
	Input_basename=$(basename "$Input_file")
	cp "${Input_file}.split${TaskNO}" "$LigandDIR/"
	Input=$LigandDIR/"${Input_basename}.split${TaskNO}"
else
	echo "Running as a regular job, processing the entire file"

	#Setup ligand directory
	mkdir -p ./Ligand_yamls
	LigandDIR=$Output_Dir/Ligand_yamls
	
	#Copy Input file to new directory
	cp $Input_file "$LigandDIR/"
	Input="$LigandDIR/$(basename "$Input_file")"
fi

echo "Processing input file: ${Input}"
echo "Number of compounds: $(wc -l < $Input)"

#Get the fasta sequence of the protein
sequence=$(cat $Prot_Fasta | tail -n +2 | tr -d '\n')
	
	#Pull the smiles and names from the input file and make affinity yaml
	for i in $(seq 1 $(wc -l < "$Input")); 
	do 
		line=$(sed "${i}q;d" $Input); 
		smile=$(echo $line | awk '{ print $1 }'); 
		name=$(echo $line | awk '{ print $2 }'); 
		echo "Processing compound $i: $name"

		#Create YAML file for this compound
		yq ".sequences[0].protein.sequence = \"$sequence\" | .sequences[1].ligand.smiles = \"${smile}\"" ~/Software/boltz/affinity_template.yaml > ./${name}_affinity.yaml; 
		
		boltz predict "${name}_affinity.yaml" --use_msa_server
		
		echo "finished prediction on ${name}"
	done
